import { fireEvent, render, screen } from "@testing-library/react";
import { beforeEach, describe, expect, it, vi } from "vitest";
import { LiveInterview } from "@/components/interview/live-interview";
import { interviewService } from "@/services/interview-service";
import type { Interview } from "@/types/interview";

vi.mock("next/link", () => ({ default: ({ children, href }: { children: React.ReactNode; href: string }) => <a href={href}>{children}</a> }));
vi.mock("@/services/interview-service", () => ({ interviewService: { get: vi.fn(), answer: vi.fn(), complete: vi.fn(), abandon: vi.fn() } }));
const active: Interview = {
  id: "session-123", fieldCategory: "IT", interviewDomain: "JAVA", customDomain: null, topic: "Spring APIs", difficulty: "MEDIUM", interviewMode: "TECHNICAL", targetRole: "Java Developer", experienceLevel: "JUNIOR", totalQuestions: 5, currentQuestionNumber: 1, followUpCount: 0, progressPercentage: 20, status: "IN_PROGRESS", overallScore: null, startedAt: "2026-08-17T12:00:00Z", completedAt: null, createdAt: "2026-08-17T12:00:00Z", updatedAt: "2026-08-17T12:00:00Z",
  messages: [{ id: 1, role: "ASSISTANT", content: "Explain dependency injection.", sequenceNumber: 1, questionNumber: 1, questionCategory: "Spring", createdAt: "2026-08-17T12:00:00Z" }],
};
const withAnswer: Interview = { ...active, currentQuestionNumber: 2, progressPercentage: 40, messages: [...active.messages, { id: 2, role: "USER", content: "Dependencies are supplied externally.", sequenceNumber: 2, questionNumber: 1, questionCategory: null, answerEvaluation: "STRONG", createdAt: "2026-08-17T12:01:00Z" }, { id: 3, role: "ASSISTANT", content: "How does constructor injection help testing?", sequenceNumber: 3, questionNumber: 2, questionCategory: "Spring", createdAt: "2026-08-17T12:01:01Z" }] };

async function renderLive(value = active) { vi.mocked(interviewService.get).mockResolvedValue(value); render(<LiveInterview sessionId="session-123"/>); await screen.findByText("Explain dependency injection."); }
describe("LiveInterview", () => {
  beforeEach(() => vi.clearAllMocks());
  it("restores and displays the authoritative session without exposing evaluation details", async () => { await renderLive(withAnswer); expect(interviewService.get).toHaveBeenCalledWith("session-123"); expect(screen.getByText("How does constructor injection help testing?")).toBeInTheDocument(); expect(screen.getByText("Dependencies are supplied externally.")).toBeInTheDocument(); expect(screen.getByText("Question 2 of 5")).toBeInTheDocument(); expect(screen.queryByText("STRONG")).not.toBeInTheDocument(); });
  it("submits once, locks duplicate submissions, and shows AI loading", async () => { let resolve!: (value: Interview) => void; vi.mocked(interviewService.answer).mockReturnValue(new Promise(resolvePromise => { resolve = resolvePromise; })); await renderLive(); fireEvent.change(screen.getByLabelText("Your answer"), { target: { value: "Dependencies are supplied externally." } }); const submit = screen.getByRole("button", { name: /Submit answer/ }); fireEvent.click(submit); fireEvent.click(submit); expect(interviewService.answer).toHaveBeenCalledTimes(1); expect(screen.getByText("AI is evaluating your answer…")).toBeInTheDocument(); resolve(withAnswer); await screen.findByText("How does constructor injection help testing?"); expect(screen.getByLabelText("Your answer")).toHaveValue(""); });
  it("preserves an answer and displays an API failure", async () => { vi.mocked(interviewService.answer).mockRejectedValue({ isAxiosError: true, response: { data: { status: 503, error: "AI unavailable", message: "The AI interviewer is temporarily unavailable." } } }); await renderLive(); const field = screen.getByLabelText("Your answer"); fireEvent.change(field, { target: { value: "Keep my answer" } }); fireEvent.click(screen.getByRole("button", { name: /Submit answer/ })); expect(await screen.findByText("The AI interviewer is temporarily unavailable.")).toBeInTheDocument(); expect(field).toHaveValue("Keep my answer"); });
  it("confirms and completes an interview", async () => { vi.mocked(interviewService.complete).mockResolvedValue({ ...active, status: "COMPLETED", completedAt: "2026-08-17T12:05:00Z" }); await renderLive(); fireEvent.click(screen.getByRole("button", { name: "End interview" })); expect(screen.getByRole("dialog")).toBeInTheDocument(); fireEvent.click(screen.getByRole("button", { name: "Complete interview" })); expect(await screen.findByText("Interview complete")).toBeInTheDocument(); expect(screen.queryByLabelText("Your answer")).not.toBeInTheDocument(); });
  it("confirms and abandons an interview", async () => { vi.mocked(interviewService.abandon).mockResolvedValue({ ...active, status: "ABANDONED", completedAt: "2026-08-17T12:05:00Z" }); await renderLive(); fireEvent.click(screen.getByRole("button", { name: "Abandon" })); fireEvent.click(screen.getByRole("button", { name: "Abandon interview" })); expect(await screen.findByText("Interview abandoned")).toBeInTheDocument(); expect(interviewService.abandon).toHaveBeenCalledWith("session-123"); });
  it("handles an invalid or unauthorized session with retry", async () => { vi.mocked(interviewService.get).mockRejectedValue({ isAxiosError: true, response: { data: { status: 404, error: "Not Found", message: "Interview not found." } } }); render(<LiveInterview sessionId="missing"/>); expect(await screen.findByText("Interview not found.")).toBeInTheDocument(); expect(screen.getByRole("button", { name: "Try again" })).toBeInTheDocument(); });
});
