"use client";
import { Activity, Award, BriefcaseBusiness, CheckCircle2, Code2, Percent, Target, Trophy } from "lucide-react";
import Link from "next/link";
import { useEffect, useState } from "react";
import { InterviewCard } from "@/components/dashboard/interview-card";
import { PerformanceCharts } from "@/components/dashboard/performance-charts";
import { ErrorState, LoadingState } from "@/components/ui/status";
import { useAuth } from "@/contexts/auth-context";
import { getApiError } from "@/lib/api-error";
import { dashboardService } from "@/services/dashboard-service";
import type { DashboardPerformance, DashboardSummary } from "@/types/dashboard";
export function DashboardView() {
  const { user } = useAuth(); const [summary, setSummary] = useState<DashboardSummary | null>(null); const [performance, setPerformance] = useState<DashboardPerformance | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  const load = () => { setLoading(true); setError(""); Promise.all([dashboardService.summary(), dashboardService.performance()]).then(([nextSummary, nextPerformance]) => { setSummary(nextSummary); setPerformance(nextPerformance); }).catch(requestError => setError(getApiError(requestError, "Unable to load your dashboard. Please try again.").message)).finally(() => setLoading(false)); };
  useEffect(() => { Promise.all([dashboardService.summary(), dashboardService.performance()]).then(([nextSummary, nextPerformance]) => { setSummary(nextSummary); setPerformance(nextPerformance); }).catch(requestError => setError(getApiError(requestError, "Unable to load your dashboard. Please try again.").message)).finally(() => setLoading(false)); }, []);
  if (loading) return <LoadingState label="Loading your dashboard…"/>; if (error || !summary || !performance) return <ErrorState message={error || "Dashboard data is unavailable."} onRetry={load}/>;
  const stats = [[Target, "Total interviews", summary.totalInterviews], [CheckCircle2, "Completed", summary.completedInterviews], [Activity, "Active", summary.activeInterviews], [Code2, "IT interviews", summary.itInterviewCount], [BriefcaseBusiness, "Non-IT interviews", summary.nonItInterviewCount], [Award, "Average score", summary.averageScore === null ? "—" : summary.averageScore.toFixed(1)], [Trophy, "Highest score", summary.highestScore ?? "—"], [Percent, "Pass percentage", `${summary.passPercentage.toFixed(1)}%`]] as const;
  return <div><div className="flex flex-wrap items-end justify-between gap-5"><div><p className="text-sm font-semibold tracking-widest text-blue-400">YOUR WORKSPACE</p><h1 className="mt-3 text-4xl font-bold">Welcome, {user?.fullName?.split(" ")[0] || "there"}</h1><p className="mt-2 text-zinc-400">Track your practice and turn feedback into steady progress.</p></div><Link className="rounded-md bg-blue-600 px-4 py-3 font-semibold hover:bg-blue-500" href="/interview/setup">Start an interview</Link></div>{summary.totalInterviews === 0 ? <section className="mt-10 rounded-xl border border-dashed border-zinc-700 bg-zinc-950 p-10 text-center"><h2 className="text-2xl font-bold">Your interview journey starts here</h2><p className="mx-auto mt-3 max-w-xl text-zinc-400">Complete your first IT or Non-IT practice session to populate analytics, history, and performance insights.</p><Link className="mt-6 inline-block font-semibold text-blue-400" href="/interview/setup">Set up your first interview</Link></section> : <><section aria-label="Dashboard statistics" className="mt-10 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{stats.map(([Icon,label,value]) => <article className="rounded-xl border border-zinc-800 bg-zinc-950 p-5" key={label}><Icon aria-hidden className="text-blue-400" size={20}/><p className="mt-4 text-sm text-zinc-400">{label}</p><p className="mt-1 text-3xl font-bold">{value}</p></article>)}</section><section className="mt-10 grid gap-4 sm:grid-cols-2"><article className="rounded-xl border border-zinc-800 bg-zinc-950 p-5"><p className="text-sm text-zinc-400">Strongest domain</p><p className="mt-2 text-xl font-semibold">{summary.strongestDomain || "Not enough data"}</p></article><article className="rounded-xl border border-zinc-800 bg-zinc-950 p-5"><p className="text-sm text-zinc-400">Focus domain</p><p className="mt-2 text-xl font-semibold">{summary.weakestDomain || "Not enough data"}</p></article></section><section className="mt-12"><div className="mb-5 flex items-center justify-between"><h2 className="text-2xl font-bold">Performance</h2><Link className="text-sm font-semibold text-blue-400" href="/history">View history</Link></div><PerformanceCharts performance={performance}/></section><section className="mt-12"><h2 className="text-2xl font-bold">Recent interviews</h2><div className="mt-5 grid gap-4 md:grid-cols-2">{summary.recentInterviews.map(interview => <InterviewCard interview={interview} key={interview.id}/>)}</div></section></>}</div>;
}
