CREATE TABLE interview_reports (
    id BIGINT NOT NULL AUTO_INCREMENT,
    interview_session_id CHAR(36) NOT NULL,
    overall_score INT NOT NULL,
    technical_accuracy_score INT NULL,
    conceptual_understanding_score INT NULL,
    problem_solving_score INT NULL,
    communication_score INT NULL,
    confidence_score INT NULL,
    situational_judgement_score INT NULL,
    role_understanding_score INT NULL,
    strengths TEXT NOT NULL,
    weaknesses TEXT NOT NULL,
    revision_areas TEXT NOT NULL,
    verdict TEXT NOT NULL,
    recommendation VARCHAR(20) NOT NULL,
    question_feedback_json LONGTEXT NOT NULL,
    generated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    CONSTRAINT fk_interview_reports_session FOREIGN KEY (interview_session_id) REFERENCES interview_sessions (id) ON DELETE CASCADE,
    CONSTRAINT chk_interview_reports_recommendation CHECK (recommendation IN ('PASS', 'FAIL')),
    CONSTRAINT chk_interview_reports_overall_score CHECK (overall_score BETWEEN 0 AND 100),
    CONSTRAINT chk_interview_reports_technical_score CHECK (technical_accuracy_score IS NULL OR technical_accuracy_score BETWEEN 0 AND 100),
    CONSTRAINT chk_interview_reports_conceptual_score CHECK (conceptual_understanding_score IS NULL OR conceptual_understanding_score BETWEEN 0 AND 100),
    CONSTRAINT chk_interview_reports_problem_score CHECK (problem_solving_score IS NULL OR problem_solving_score BETWEEN 0 AND 100),
    CONSTRAINT chk_interview_reports_communication_score CHECK (communication_score IS NULL OR communication_score BETWEEN 0 AND 100),
    CONSTRAINT chk_interview_reports_confidence_score CHECK (confidence_score IS NULL OR confidence_score BETWEEN 0 AND 100),
    CONSTRAINT chk_interview_reports_situational_score CHECK (situational_judgement_score IS NULL OR situational_judgement_score BETWEEN 0 AND 100),
    CONSTRAINT chk_interview_reports_role_score CHECK (role_understanding_score IS NULL OR role_understanding_score BETWEEN 0 AND 100)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci;

