"use client";
import { CheckCircle2, FileText, RotateCcw, XCircle } from "lucide-react";
import Link from "next/link";
import { useEffect, useState } from "react";
import { Button } from "@/components/ui/button";
import { ErrorState, LoadingState } from "@/components/ui/status";
import { getApiError } from "@/lib/api-error";
import { optionLabel } from "@/lib/interview-labels";
import { interviewService } from "@/services/interview-service";
import { reportService } from "@/services/report-service";
import type { Interview } from "@/types/interview";
import type { InterviewReport } from "@/types/report";

function scoreColour(score: number) { return score >= 70 ? "text-green-400" : score >= 50 ? "text-yellow-400" : "text-red-400"; }
function duration(interview: Interview) { if (!interview.startedAt || !interview.completedAt) return "—"; const seconds = Math.max(0, Math.floor((new Date(interview.completedAt).getTime() - new Date(interview.startedAt).getTime()) / 1000)); return `${Math.floor(seconds / 60)}m ${seconds % 60}s`; }
export function ReportView({ sessionId }: { sessionId: string }) {
  const [interview, setInterview] = useState<Interview | null>(null); const [report, setReport] = useState<InterviewReport | null>(null); const [loading, setLoading] = useState(true); const [generating, setGenerating] = useState(false); const [error, setError] = useState("");
  const load = () => { setLoading(true); setError(""); interviewService.get(sessionId).then(async session => { setInterview(session); if (session.status === "REPORT_GENERATED") setReport(await reportService.get(sessionId)); }).catch(requestError => setError(getApiError(requestError, "Unable to load this report.").message)).finally(() => setLoading(false)); };
  useEffect(() => { interviewService.get(sessionId).then(async session => { setInterview(session); if (session.status === "REPORT_GENERATED") setReport(await reportService.get(sessionId)); }).catch(requestError => setError(getApiError(requestError, "Unable to load this report.").message)).finally(() => setLoading(false)); }, [sessionId]);
  const generate = async () => { if (generating) return; setGenerating(true); setError(""); try { setReport(await reportService.generate(sessionId)); setInterview(current => current ? { ...current, status: "REPORT_GENERATED" } : current); } catch (requestError) { setError(getApiError(requestError, "Unable to generate the report. Please try again.").message); } finally { setGenerating(false); } };
  if (loading) return <LoadingState label="Loading interview results…"/>; if (error && !interview) return <ErrorState message={error} onRetry={load}/>; if (!interview) return <ErrorState message="Interview not found." onRetry={load}/>;
  if (interview.status === "IN_PROGRESS" || interview.status === "CREATED") return <section className="rounded-xl border border-yellow-900 bg-yellow-950/30 p-8 text-center"><h1 className="text-2xl font-bold">Interview still in progress</h1><p className="mt-3 text-zinc-400">Complete the session before generating its evaluation report.</p><Link className="mt-5 inline-block font-semibold text-blue-400" href={`/interview/${sessionId}`}>Continue interview</Link></section>;
  if (interview.status === "ABANDONED") return <section className="rounded-xl border border-red-900 bg-red-950/30 p-8 text-center"><h1 className="text-2xl font-bold">No report available</h1><p className="mt-3 text-zinc-400">Abandoned interviews cannot generate evaluation reports.</p><Link className="mt-5 inline-block font-semibold text-blue-400" href="/history">Return to history</Link></section>;
  if (!report) return <section className="mx-auto max-w-2xl rounded-xl border border-zinc-800 bg-zinc-950 p-8 text-center"><FileText aria-hidden className="mx-auto text-blue-400" size={40}/><h1 className="mt-5 text-3xl font-bold">Interview complete</h1><p className="mt-3 text-zinc-400">Generate your detailed AI evaluation for strengths, improvements, revision areas, and question-level feedback.</p>{error && <div className="mt-5"><ErrorState message={error}/></div>}<Button className="mt-6" disabled={generating} onClick={() => void generate()} type="button">{generating ? "Generating report…" : "Generate report"}</Button></section>;
  const scores = [["Technical accuracy", report.technicalAccuracyScore], ["Conceptual understanding", report.conceptualUnderstandingScore], ["Problem solving", report.problemSolvingScore], ["Communication", report.communicationScore], ["Confidence", report.confidenceScore], ["Situational judgement", report.situationalJudgementScore], ["Role understanding", report.roleUnderstandingScore]].filter((item): item is [string, number] => item[1] !== null);
  return <div><section className="text-center"><p className="text-sm font-semibold tracking-widest text-blue-400">INTERVIEW COMPLETE</p><div className="mt-4 flex justify-center">{report.recommendation === "PASS" ? <CheckCircle2 aria-hidden className="text-green-400" size={50}/> : <XCircle aria-hidden className="text-red-400" size={50}/>}</div><h1 className="mt-4 text-4xl font-bold">{report.recommendation === "PASS" ? "You passed" : "Keep building"}</h1><p className="mt-2 text-zinc-400">{report.scoreInterpretation}</p><p className={`mt-5 text-7xl font-bold ${scoreColour(report.overallScore)}`}>{report.overallScore}</p><p className="mt-1 text-sm text-zinc-500">Overall score out of 100</p></section>
    <section className="mt-10 grid gap-3 rounded-xl border border-zinc-800 bg-zinc-950 p-5 sm:grid-cols-2 lg:grid-cols-4">{[["Field", interview.fieldCategory === "IT" ? "IT Field" : "Non-IT Field"], ["Domain", interview.customDomain || optionLabel([], interview.interviewDomain)], ["Role", interview.targetRole], ["Difficulty", optionLabel([], interview.difficulty)], ["Mode", optionLabel([], interview.interviewMode)], ["Experience", optionLabel([], interview.experienceLevel)], ["Duration", duration(interview)], ["Generated", new Date(report.generatedAt).toLocaleDateString()]].map(([label,value]) => <div key={label}><p className="text-xs text-zinc-500">{label}</p><p className="mt-1 font-semibold">{value}</p></div>)}</section>
    <section aria-label="Category scores" className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{scores.map(([label,score]) => <article className="rounded-xl border border-zinc-800 bg-zinc-950 p-5" key={label}><p className="text-sm text-zinc-400">{label}</p><p className={`mt-2 text-3xl font-bold ${scoreColour(score)}`}>{score}</p></article>)}</section>
    <section className="mt-8 grid gap-6 lg:grid-cols-3"><List title="Strengths" values={report.strengths} colour="text-green-400"/><List title="Improvements" values={report.weaknesses} colour="text-yellow-400"/><List title="Revision areas" values={report.revisionAreas} colour="text-blue-400"/></section>
    <section className="mt-8 rounded-xl border border-zinc-800 bg-zinc-950 p-6"><h2 className="text-2xl font-bold">Verdict</h2><p className="mt-3 leading-7 text-zinc-300">{report.verdict}</p></section>
    <section className="mt-10"><h2 className="text-2xl font-bold">Question-by-question feedback</h2><div className="mt-5 grid gap-4">{report.questionFeedback.map((item,index) => <article className="rounded-xl border border-zinc-800 bg-zinc-950 p-6" key={`${index}-${item.question}`}><div className="flex flex-wrap items-center justify-between gap-3"><h3 className="font-semibold">Question {index + 1}</h3><span className="rounded-full border border-zinc-700 px-3 py-1 text-xs">{optionLabel([], item.evaluation)}</span></div><p className="mt-3 leading-7">{item.question}</p><p className="mt-4 text-sm font-semibold text-zinc-400">Your answer</p><p className="mt-1 leading-7 text-zinc-300">{item.answerSummary}</p><p className="mt-4 text-sm font-semibold text-zinc-400">Feedback</p><p className="mt-1 leading-7 text-zinc-300">{item.feedback}</p></article>)}</div></section>
    <div className="mt-10 flex flex-wrap justify-center gap-4"><Link className="inline-flex items-center gap-2 rounded-md bg-blue-600 px-4 py-3 font-semibold hover:bg-blue-500" href="/interview/setup"><RotateCcw aria-hidden size={18}/>Start new interview</Link><Link className="rounded-md border border-zinc-700 px-4 py-3 font-semibold" href="/dashboard">Back to dashboard</Link></div></div>;
}
function List({ title, values, colour }: { title: string; values: string[]; colour: string }) { return <article className="rounded-xl border border-zinc-800 bg-zinc-950 p-6"><h2 className={`text-xl font-bold ${colour}`}>{title}</h2>{values.length ? <ul className="mt-4 grid gap-3 text-zinc-300">{values.map(value => <li className="flex gap-2" key={value}><span aria-hidden>•</span><span>{value}</span></li>)}</ul> : <p className="mt-4 text-zinc-500">No items reported.</p>}</article>; }
