import { fireEvent, render, screen } from "@testing-library/react";
import { beforeEach, describe, expect, it, vi } from "vitest";
import { ReportView } from "@/components/report/report-view";
import { interviewService } from "@/services/interview-service";
import { reportService } from "@/services/report-service";
import type { Interview } from "@/types/interview";
import type { InterviewReport } from "@/types/report";
vi.mock("@/services/interview-service", () => ({ interviewService: { get: vi.fn() } }));
vi.mock("@/services/report-service", () => ({ reportService: { get: vi.fn(), generate: vi.fn() } }));
const interview: Interview = { id: "one", fieldCategory: "IT", interviewDomain: "JAVA", customDomain: null, topic: "Spring APIs", difficulty: "MEDIUM", interviewMode: "TECHNICAL", targetRole: "Developer", experienceLevel: "JUNIOR", totalQuestions: 5, currentQuestionNumber: 5, followUpCount: 0, progressPercentage: 100, status: "REPORT_GENERATED", overallScore: 82, startedAt: "2026-08-17T12:00:00Z", completedAt: "2026-08-17T12:10:30Z", createdAt: "2026-08-17T12:00:00Z", updatedAt: "2026-08-17T12:10:30Z", messages: [] };
const report: InterviewReport = { id: 1, sessionId: "one", fieldCategory: "IT", overallScore: 82, scoreInterpretation: "Good", technicalAccuracyScore: 84, conceptualUnderstandingScore: 80, problemSolvingScore: 81, communicationScore: 83, confidenceScore: 78, situationalJudgementScore: null, roleUnderstandingScore: null, strengths: ["Clear concepts"], weaknesses: ["Add examples"], revisionAreas: ["Transactions"], verdict: "Strong overall interview.", recommendation: "PASS", questionFeedback: [{ question: "What is DI?", answerSummary: "Supplying dependencies.", evaluation: "STRONG", feedback: "Clear and accurate." }], generatedAt: "2026-08-17T12:11:00Z" };
describe("ReportView", () => {
  beforeEach(() => vi.clearAllMocks());
  it("renders complete category-aware report details", async () => { vi.mocked(interviewService.get).mockResolvedValue(interview); vi.mocked(reportService.get).mockResolvedValue(report); render(<ReportView sessionId="one"/>); expect(await screen.findByText("You passed")).toBeInTheDocument(); expect(screen.getByText("82")).toHaveClass("text-green-400"); expect(screen.getByText("Technical accuracy")).toBeInTheDocument(); expect(screen.queryByText("Situational judgement")).not.toBeInTheDocument(); expect(screen.getByText("Strong overall interview.")).toBeInTheDocument(); expect(screen.getByText("What is DI?")).toBeInTheDocument(); expect(screen.getByText("10m 30s")).toBeInTheDocument(); });
  it("generates a report only after user action", async () => { vi.mocked(interviewService.get).mockResolvedValue({ ...interview, status: "COMPLETED" }); vi.mocked(reportService.generate).mockResolvedValue(report); render(<ReportView sessionId="one"/>); expect(await screen.findByText("Interview complete")).toBeInTheDocument(); expect(reportService.generate).not.toHaveBeenCalled(); fireEvent.click(screen.getByRole("button", { name: "Generate report" })); expect(await screen.findByText("You passed")).toBeInTheDocument(); expect(reportService.generate).toHaveBeenCalledWith("one"); });
  it("handles active, abandoned, and unavailable reports", async () => { vi.mocked(interviewService.get).mockResolvedValue({ ...interview, status: "IN_PROGRESS" }); const { unmount } = render(<ReportView sessionId="one"/>); expect(await screen.findByText("Interview still in progress")).toBeInTheDocument(); unmount(); vi.mocked(interviewService.get).mockResolvedValue({ ...interview, status: "ABANDONED" }); render(<ReportView sessionId="two"/>); expect(await screen.findByText("No report available")).toBeInTheDocument(); });
});
