"use client";
import { Award, BriefcaseBusiness, Code2, Mail, UserRound } from "lucide-react";
import { useEffect, useState } from "react";
import { Button } from "@/components/ui/button";
import { ErrorState, LoadingState } from "@/components/ui/status";
import { useAuth } from "@/contexts/auth-context";
import { getApiError } from "@/lib/api-error";
import { dashboardService } from "@/services/dashboard-service";
import { profileService } from "@/services/profile-service";
import type { DashboardSummary } from "@/types/dashboard";
import type { Profile } from "@/types/profile";

export function ProfileView() {
  const { updateUser } = useAuth(); const [profile, setProfile] = useState<Profile | null>(null); const [summary, setSummary] = useState<DashboardSummary | null>(null); const [name, setName] = useState(""); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState(""); const [nameError, setNameError] = useState(""); const [success, setSuccess] = useState("");
  const load = () => { setLoading(true); setError(""); Promise.all([profileService.get(), dashboardService.summary()]).then(([nextProfile, nextSummary]) => { setProfile(nextProfile); setSummary(nextSummary); setName(nextProfile.fullName); }).catch(requestError => setError(getApiError(requestError, "Unable to load your profile.").message)).finally(() => setLoading(false)); };
  useEffect(() => { Promise.all([profileService.get(), dashboardService.summary()]).then(([nextProfile, nextSummary]) => { setProfile(nextProfile); setSummary(nextSummary); setName(nextProfile.fullName); }).catch(requestError => setError(getApiError(requestError, "Unable to load your profile.").message)).finally(() => setLoading(false)); }, []);
  const save = async (event: React.FormEvent) => { event.preventDefault(); const clean = name.trim(); setNameError(""); setSuccess(""); if (!clean) { setNameError("Full name is required."); return; } if (clean.length > 120) { setNameError("Full name must not exceed 120 characters."); return; } setSaving(true); try { const updated = await profileService.update(clean); setProfile(updated); setName(updated.fullName); updateUser({ id: updated.id, fullName: updated.fullName, email: updated.email }); setSuccess("Profile updated successfully."); } catch (requestError) { const response = getApiError(requestError, "Unable to update your profile."); setNameError(response.fieldErrors?.fullName ?? ""); setError(response.message); } finally { setSaving(false); } };
  if (loading) return <LoadingState label="Loading your profile…"/>; if (error && !profile) return <ErrorState message={error} onRetry={load}/>; if (!profile || !summary) return <ErrorState message="Profile data is unavailable." onRetry={load}/>;
  const stats = [[Award, "Total interviews", summary.totalInterviews], [Award, "Average score", summary.averageScore === null ? "—" : summary.averageScore.toFixed(1)], [Code2, "IT interviews", summary.itInterviewCount], [BriefcaseBusiness, "Non-IT interviews", summary.nonItInterviewCount]] as const;
  return <div><p className="text-sm font-semibold tracking-widest text-blue-400">YOUR ACCOUNT</p><h1 className="mt-3 text-4xl font-bold">Profile</h1><div className="mt-8 grid gap-6 lg:grid-cols-[1fr_1.3fr]"><section className="rounded-xl border border-zinc-800 bg-zinc-950 p-6"><div className="grid h-14 w-14 place-items-center rounded-full bg-blue-950 text-blue-400"><UserRound aria-hidden/></div><h2 className="mt-5 text-2xl font-bold">{profile.fullName}</h2><p className="mt-2 flex items-center gap-2 text-zinc-400"><Mail aria-hidden size={17}/>{profile.email}</p><p className="mt-5 text-sm text-zinc-500">Member since {new Date(profile.createdAt).toLocaleDateString(undefined, { year: "numeric", month: "long", day: "numeric" })}</p></section><form className="rounded-xl border border-zinc-800 bg-zinc-950 p-6" onSubmit={save}><h2 className="text-xl font-bold">Account details</h2><p className="mt-2 text-sm text-zinc-400">Update the name shown throughout your workspace.</p>{error && <div className="mt-4"><ErrorState message={error}/></div>}{success && <p className="mt-4 rounded-md border border-green-900 bg-green-950/30 p-3 text-sm text-green-300" role="status">{success}</p>}<div className="mt-6 grid gap-2"><label className="text-sm font-medium" htmlFor="profileName">Full name</label><input aria-invalid={Boolean(nameError)} className="min-h-11 rounded-md border border-zinc-700 bg-zinc-900 px-3" id="profileName" maxLength={120} onChange={event => { setName(event.target.value); setNameError(""); setError(""); setSuccess(""); }} value={name}/>{nameError && <p className="text-sm text-red-400" role="alert">{nameError}</p>}</div><div className="mt-5 grid gap-2"><label className="text-sm font-medium" htmlFor="profileEmail">Email</label><input className="min-h-11 rounded-md border border-zinc-800 bg-zinc-900 px-3 text-zinc-500" disabled id="profileEmail" value={profile.email}/></div><Button className="mt-6" disabled={saving || name.trim() === profile.fullName} type="submit">{saving ? "Saving…" : "Save changes"}</Button></form></div><section aria-label="Profile statistics" className="mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{stats.map(([Icon,label,value]) => <article className="rounded-xl border border-zinc-800 bg-zinc-950 p-5" key={label}><Icon aria-hidden className="text-blue-400" size={20}/><p className="mt-3 text-sm text-zinc-400">{label}</p><p className="mt-1 text-2xl font-bold">{value}</p></article>)}</section></div>;
}
